const data = {
    products: [
        {
            _id:'1',
            name:"Nike",
            category:"Bascket",
            image:"/images/product-1.jpg",
            price:70,
            brand:"Nike",
            rating:4.5,
            numReviews:10,
            description:"High quality shoes",
        },
        {
            _id:'2',
            name:"Adidas",
            category:"short",
            image:"/images/product-1.jpg",
            price:70,
            brand:"Nike",
            rating:4.5,
            numReviews:10,
            description:"High quality shoes",
        },
        {
            _id:'3',
            name:"New Balance",
            category:"Bascket",
            image:"/images/product-1.jpg",
            price:230,
            brand:"Nike",
            rating:3,
            numReviews:10,
            description:"High quality new balance",
        },
        {
            _id:'4',
            name:"Lacoste",
            category:"T-shirt",
            image:"/images/product-1.jpg",
            price:180,
            brand:"Nike",
            rating:4.5,
            numReviews:10,
            description:"High quality lacoste",
        },
        {
            _id:'5',
            name:"Puma",
            category:"Lunette",
            image:"/images/product-1.jpg",
            price:90,
            brand:"Nike",
            rating:2.5,
            numReviews:10,
            description:"High quality puma",
        },
        {
            _id:'6',
            name:"Polo",
            category:"short",
            image:"/images/product-1.jpg",
            price:220,
            brand:"Nike",
            rating:4,
            numReviews:10,
            description:"High quality polo",
        },
    ]
}