const data = {
    products: [
        {
            _id:'1',
            name:"T-shirt Celio",
            category:"T-shirt",
            image:"/images/product-1.avif",
            price:70,
            brand:"Celio",
            rating:4.5,
            numReviews:10,
            description:"T-shirt Celio 2020 noir",
        },
        {
            _id:'2',
            name:"Jeans Celio ",
            category:"Pantalon",
            image:"/images/product-2.avif",
            price:70,
            brand:"Celio",
            rating:4.5,
            numReviews:10,
            description:"Blue jeans Celio 2020",
        },
        {
            _id:'3',
            name:"Polo maille Celio",
            category:"Bascket",
            image:"/images/product-3.avif",
            price:230,
            brand:"Nike",
            rating:3,
            numReviews:10,
            description:"Polo maille Celio 2020",
        },
        {
            _id:'4',
            name:"Hangover blouse Celio",
            category:"Collection hiver",
            image:"/images/product-4.avif",
            price:180,
            brand:"Celio",
            rating:4.5,
            numReviews:10,
            description:"Hangover blouse Celio 2020",
        },
        {
            _id:'5',
            name:"Veste Celio",
            category:"Veste",
            image:"/images/product-5.avif",
            price:90,
            brand:"Celio",
            rating:2.5,
            numReviews:10,
            description:"Veste printemps Celio",
        },
        {
            _id:'6',
            name:"Blouson hiver Celio",
            category:"Blouson",
            image:"/images/product-6.avif",
            price:220,
            brand:"Celio",
            rating:4,
            numReviews:10,
            description:"Blouson fourrure interne Celio",
        },
        {
            _id:'5',
            name:"Veste Celio",
            category:"Veste",
            image:"/images/product-7.avif",
            price:90,
            brand:"Celio",
            rating:2.5,
            numReviews:10,
            description:"Veste printemps Celio",
        },
        {
            _id:'6',
            name:"Blouson hiver Celio",
            category:"Blouson",
            image:"/images/product-8.avif",
            price:220,
            brand:"Celio",
            rating:4,
            numReviews:10,
            description:"Blouson fourrure interne Celio",
        },
    ]
}

export default data;